load sampleRTT;
load estimatedRTT;
load timeoutInterval;
plot(sampleRTT, '--*', 'Color', 'b', 'LineWidth', 0.5, 'MarkerSize', 8);
hold on;
plot(estimatedRTT, '--*', 'Color', 'k', 'LineWidth', 0.5, 'MarkerSize', 8);
plot(timeoutInterval, '--*', 'Color', 'r', 'LineWidth', 0.5, 'MarkerSize', 8);
legend('sampleRTT','estimatedRTT','timeoutInterval');
grid on;
xlabel('Medición');
ylabel('Tiempo [ms]');
title('Traza hop29 alpha=1/8');
print -dpng "trazaHop29.png";
